basePath: /api/v1
definitions:
  geek.GeekCourseModel:
    properties:
      limit:
        description: 条数
        type: integer
      page:
        description: 页数
        type: integer
      typeId:
        description: 类型
        type: string
    type: object
  user.LoginModel:
    properties:
      account:
        description: 账号
        type: string
      password:
        description: 密码
        type: string
    type: object
info:
  contact: {}
  description: geek time
  title: 极客时间 API
  version: 0.0.1
paths:
  /geek/GetCourseType:
    get:
      consumes:
      - application/json
      description: 查看大课程的类别
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 课程大分类
      tags:
      - geek
  /geek/GetGeekArticle:
    post:
      consumes:
      - application/json
      description: 查看课程下的章节
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 参数
        in: body
        name: GeekCourseModel
        required: true
        schema:
          $ref: '#/definitions/geek.GeekCourseModel'
      produces:
      - application/json
      responses: {}
      summary: 章节查看
      tags:
      - geek
  /geek/GetGeekCourse:
    post:
      consumes:
      - application/json
      description: 查看大分类下的课程
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 参数
        in: body
        name: GeekCourseModel
        required: true
        schema:
          $ref: '#/definitions/geek.GeekCourseModel'
      produces:
      - application/json
      responses: {}
      summary: 课程查看
      tags:
      - geek
  /user/{id}:
    get:
      consumes:
      - application/json
      description: 根据传递的name查找来用户，可能返回一个或多个用户数据
      parameters:
      - description: int valid
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 查询用户
      tags:
      - user
  /user/add:
    post:
      consumes:
      - application/json
      description: 添加一个用户
      produces:
      - application/json
      responses: {}
      summary: 添加一个用户
      tags:
      - user
  /user/delete/{id}:
    get:
      consumes:
      - application/json
      description: 根据传递的id查找来删除用户
      produces:
      - application/json
      responses: {}
      summary: 删除用户
      tags:
      - user
  /user/list:
    get:
      consumes:
      - application/json
      description: 根据传分页信息查询用户列表
      produces:
      - application/json
      responses: {}
      summary: 用户列表
      tags:
      - user
  /user/list/{name}:
    get:
      consumes:
      - application/json
      description: 根据传递的name查找来用户，可能返回一个或多个用户数据
      produces:
      - application/json
      responses: {}
      summary: 查询用户
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      description: 根据用户的账号和密码
      parameters:
      - description: User information
        in: body
        name: loginModel
        required: true
        schema:
          $ref: '#/definitions/user.LoginModel'
      produces:
      - application/json
      responses: {}
      summary: 登录
      tags:
      - user
  /user/update:
    post:
      consumes:
      - application/json
      description: 根据传递的用户信息进行更新，必须要传递已存在的id
      produces:
      - application/json
      responses: {}
      summary: 修改用户
      tags:
      - user
swagger: "2.0"
